plugins {
    id 'com.android.application'
}

android {
    namespace 'com.marginalia.app'
    compileSdk 37
    buildToolsVersion "36.0.0"

    defaultConfig {
        applicationId "com.marginalia.app"
        minSdk 26
        targetSdk 37
        versionCode 5
        versionName "1.4.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.9.0'
    implementation 'com.google.android.material:material:1.11.0'
}
